//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fr_CA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr_CA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signals.Resources.Resources.fr-CA", typeof(Resources_fr_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals suit les performances de vos investissements et vous avertit des événements importants tels qu&apos;un doublement du prix ou une forte baisse en pourcentage..
        /// </summary>
        public static string AboutParagraph1 {
            get {
                return ResourceManager.GetString("AboutParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez utiliser cette application dès maintenant, telle quelle, pour suivre quelques éléments, mais pour en tirer le meilleur parti, vous devrez créer un compte auprès du fournisseur de données Finnhub. Heureusement, c&apos;est facile à faire. Cliquez sur le bouton ci-dessous pour visiter Finnhub et obtenir votre clé API gratuite dès maintenant. Vous n&apos;avez pas besoin de fournir beaucoup d&apos;informations (juste une adresse e-mail) et ils ne vous envoient pas de spam. Une fois que vous avez votre clé, saisisse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutParagraph2 {
            get {
                return ResourceManager.GetString("AboutParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals ouse Money Trader ne fournit pas de conseils en matière d&apos;investissement. En utilisant cette application, vous assumez l&apos;entière responsabilité de vos propres décisions d&apos;investissement et de la performance de vos investissements..
        /// </summary>
        public static string AboutParagraph3 {
            get {
                return ResourceManager.GetString("AboutParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La version actuelle est la 1.0 publiée en 2025.
        /// </summary>
        public static string ApplicationVersionStatement {
            get {
                return ResourceManager.GetString("ApplicationVersionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ignal$.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regardez ce qui se passe.
        /// </summary>
        public static string TagLine {
            get {
                return ResourceManager.GetString("TagLine", resourceCulture);
            }
        }
    }
}
