//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signals.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals empowers you to stay ahead of your financial goals by tracking stocks and ETFs like SPY and SPX in real time, with customizable alerts for significant price changes, such as doubling or a 25% drop..
        /// </summary>
        public static string AboutParagraph1 {
            get {
                return ResourceManager.GetString("AboutParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals is not a trading app and does not connect to brokerage accounts. It offers a convenient way to monitor your investment holdings and watchlist items, powered by real-time market data from Finnhub.io. Start tracking your financial journey today!.
        /// </summary>
        public static string AboutParagraph2 {
            get {
                return ResourceManager.GetString("AboutParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access daily or real-time stock quotes, create a free Finnhub account to obtain your API key. It’s quick, requires only an email, and Finnhub won’t spam you. Click the button below to visit Finnhub.io and sign up. Then, enter your API key in the Settings page, accessible from the main menu.  Finnhub allows you 60 APO calls/minute with a free account..
        /// </summary>
        public static string AboutParagraph3 {
            get {
                return ResourceManager.GetString("AboutParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer: Signals is for informational purposes only and not intended for trading or investment decisions. Stock quotes from Finnhub.io may experience delays or inaccuracies; users assume all risks related to financial decisions. Third-party services like Finnhub.io are subject to their terms and availability. Use Signals at your own risk..
        /// </summary>
        public static string AboutParagraph4 {
            get {
                return ResourceManager.GetString("AboutParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to holdings.
        /// </summary>
        public static string AddToHoldingsLabel {
            get {
                return ResourceManager.GetString("AddToHoldingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to watchlist.
        /// </summary>
        public static string AddToWatchlistLabel {
            get {
                return ResourceManager.GetString("AddToWatchlistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version is 1.0 released 2025.
        /// </summary>
        public static string ApplicationVersionStatement {
            get {
                return ResourceManager.GetString("ApplicationVersionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ignal$.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        public static string BtnBackupDatabaseContent {
            get {
                return ResourceManager.GetString("BtnBackupDatabaseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Edit.
        /// </summary>
        public static string BtnCancelSaveKeyText {
            get {
                return ResourceManager.GetString("BtnCancelSaveKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for a new version of Signals.
        /// </summary>
        public static string BtnCheckForNewVersionContent {
            get {
                return ResourceManager.GetString("BtnCheckForNewVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Key.
        /// </summary>
        public static string BtnEditKeyText {
            get {
                return ResourceManager.GetString("BtnEditKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Key.
        /// </summary>
        public static string BtnGetKeyContent {
            get {
                return ResourceManager.GetString("BtnGetKeyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Database.
        /// </summary>
        public static string BtnRestoreDatabaseContent {
            get {
                return ResourceManager.GetString("BtnRestoreDatabaseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Key.
        /// </summary>
        public static string BtnSaveKeyText {
            get {
                return ResourceManager.GetString("BtnSaveKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string BtnSaveSettingsText {
            get {
                return ResourceManager.GetString("BtnSaveSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchased units.
        /// </summary>
        public static string BuyEventHandler_Handle_purchased_units {
            get {
                return ResourceManager.GetString("BuyEventHandler_Handle_purchased_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string HourLabel {
            get {
                return ResourceManager.GetString("HourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string KeyLabel {
            get {
                return ResourceManager.GetString("KeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string MinuteLabel {
            get {
                return ResourceManager.GetString("MinuteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New quote operation cancelled.
        /// </summary>
        public static string NewQuoteReceivedEventHandler_Handle_New_quote_operation_cancelled {
            get {
                return ResourceManager.GetString("NewQuoteReceivedEventHandler_Handle_New_quote_operation_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New quote received.
        /// </summary>
        public static string NewQuoteReceivedEventHandler_Handle_New_quote_received {
            get {
                return ResourceManager.GetString("NewQuoteReceivedEventHandler_Handle_New_quote_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price updated.
        /// </summary>
        public static string PriceUpdatedEventHandler_Handle_Price_updated {
            get {
                return ResourceManager.GetString("PriceUpdatedEventHandler_Handle_Price_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold units.
        /// </summary>
        public static string SellEventHandler_Handle_Sold_units {
            get {
                return ResourceManager.GetString("SellEventHandler_Handle_Sold_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Gain Multiplier.
        /// </summary>
        public static string SettingsDefaultHighGainMultiplierLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultHighGainMultiplierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing Stop.
        /// </summary>
        public static string SettingsDefaultTrailingStopLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultTrailingStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string SettingsDefaultUseHighGainMultiplierLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultUseHighGainMultiplierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string SettingsDefaultUseTrailingStopLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultUseTrailingStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata version.
        /// </summary>
        public static string SettingsMetadataVersionLabel {
            get {
                return ResourceManager.GetString("SettingsMetadataVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string SymbolLabel {
            get {
                return ResourceManager.GetString("SymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch what happens.
        /// </summary>
        public static string TagLine {
            get {
                return ResourceManager.GetString("TagLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitsLabel {
            get {
                return ResourceManager.GetString("UnitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased {0} units of {1} for {2} each at {3}.
        /// </summary>
        public static string WatchlistItemPageViewModel_Buy_Purchased__0__of__1__for__2__each_at__3_ {
            get {
                return ResourceManager.GetString("WatchlistItemPageViewModel_Buy_Purchased__0__of__1__for__2__each_at__3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased {0} units of {1} for {2:C} each on {3:MMMM dd yyyy} at {4:h:mm:ss tt zz}.
        /// </summary>
        public static string WatchlistItemPageViewModel_Buy_Purchased__0__units_of__1__for__2_C__each_on__3_MMMM_dd_yyyy__at__4_h_mm_ss_tt_zz_ {
            get {
                return ResourceManager.GetString("WatchlistItemPageViewModel_Buy_Purchased__0__units_of__1__for__2_C__each_on__3_MM" +
                        "MM_dd_yyyy__at__4_h_mm_ss_tt_zz_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0}.
        /// </summary>
        public static string WatchlistItemPageViewModel_DeleteWatchlistItem_Deleted__0_ {
            get {
                return ResourceManager.GetString("WatchlistItemPageViewModel_DeleteWatchlistItem_Deleted__0_", resourceCulture);
            }
        }
    }
}
