//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signals.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals tracks the performance of your investments and alerts you to significant events such as a double in price or a large percentage drop..
        /// </summary>
        public static string AboutParagraph1 {
            get {
                return ResourceManager.GetString("AboutParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll need to set up a free account with data provider Finnhub.  Fortunately, this is easy to do (and as mentioned, costs nothing for  basic service).  Click the button below to visit Finnhub and get your free API key right now.  You don&apos;t have to give a lot of information (just an email address) and they don&apos;t spam you.  Once you have your key, enter it in the application&apos;s Settings page..
        /// </summary>
        public static string AboutParagraph2 {
            get {
                return ResourceManager.GetString("AboutParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals does not provide investment advice.  By using this application, you are accepting full responsibility for making your own investment decisions and for the performance of your investments..
        /// </summary>
        public static string AboutParagraph3 {
            get {
                return ResourceManager.GetString("AboutParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to holdings.
        /// </summary>
        public static string AddToHoldingsLabel {
            get {
                return ResourceManager.GetString("AddToHoldingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to watchlist.
        /// </summary>
        public static string AddToWatchlistLabel {
            get {
                return ResourceManager.GetString("AddToWatchlistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version is 1.0 released 2025.
        /// </summary>
        public static string ApplicationVersionStatement {
            get {
                return ResourceManager.GetString("ApplicationVersionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ignal$.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        public static string BtnBackupDatabaseContent {
            get {
                return ResourceManager.GetString("BtnBackupDatabaseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Edit.
        /// </summary>
        public static string BtnCancelSaveKeyText {
            get {
                return ResourceManager.GetString("BtnCancelSaveKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for a new version of Signals.
        /// </summary>
        public static string BtnCheckForNewVersionContent {
            get {
                return ResourceManager.GetString("BtnCheckForNewVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Key.
        /// </summary>
        public static string BtnEditKeyText {
            get {
                return ResourceManager.GetString("BtnEditKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Key.
        /// </summary>
        public static string BtnGetKeyContent {
            get {
                return ResourceManager.GetString("BtnGetKeyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Database.
        /// </summary>
        public static string BtnRestoreDatabaseContent {
            get {
                return ResourceManager.GetString("BtnRestoreDatabaseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Key.
        /// </summary>
        public static string BtnSaveKeyText {
            get {
                return ResourceManager.GetString("BtnSaveKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string BtnSaveSettingsText {
            get {
                return ResourceManager.GetString("BtnSaveSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string KeyLabel {
            get {
                return ResourceManager.GetString("KeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Gain Multiplier.
        /// </summary>
        public static string SettingsDefaultHighGainMultiplierLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultHighGainMultiplierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing Stop.
        /// </summary>
        public static string SettingsDefaultTrailingStopLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultTrailingStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string SettingsDefaultUseHighGainMultiplierLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultUseHighGainMultiplierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string SettingsDefaultUseTrailingStopLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultUseTrailingStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata version.
        /// </summary>
        public static string SettingsMetadataVersionLabel {
            get {
                return ResourceManager.GetString("SettingsMetadataVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string SymbolLabel {
            get {
                return ResourceManager.GetString("SymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch what happens.
        /// </summary>
        public static string TagLine {
            get {
                return ResourceManager.GetString("TagLine", resourceCulture);
            }
        }
    }
}
